name: Commitlint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on:
      - self-hosted
      - infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm

      - name: Setup Node.js
        uses: dhl-actions-incubation/surrogate-setup-node@v0
        with:
          node-version: "lts"

      - name: Install commitlint
        run: |
          npm install -g \
            @commitlint/cli \
            @commitlint/config-conventional \
            conventional-changelog-conventionalcommits
        env:
          NPM_CONFIG_REGISTRY: https://artifactory.dhl.com/artifactory/api/npm/npm/

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: |
          npx commitlint \
            --from HEAD~1 \
            --to HEAD \
            --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint \
            --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} \
            --to ${{ github.event.pull_request.head.sha }} \
            --verbose
